In [1]:
import numpy as np

In [2]:
# Create an array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [4]:
# Create an with regularly spaced values
a_range = np.arange(0,10)
print(a_range)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Create an array with evenly spaced values
a_linspace = np.linspace(0,10,5)
print(a_linspace)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
random_uniform = np.random.rand(10)
print(random_uniform)

[0.02598765 0.58495376 0.24982591 0.41834936 0.79405447 0.35003785
 0.18158589 0.51706652 0.71971943 0.09174729]


In [14]:
random_normal = np.random.randn(10)
print(random_normal)

[ 1.76264442  1.43310582  0.26237361  1.0454941   0.10129759 -0.55909846
 -1.67923553  0.60041701  1.71591351 -0.10632274]


In [26]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
shape = np.shape(arr)
#dtype = np.dtype(arr) #int64
size = np.size(arr)
print(shape)
print(size)


[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [31]:
a = np.array([1,5,8,9,5,9,6,8])
first_element = a[0]
print(first_element)
sliced_array = a[1:4]
print(sliced_array)

1
[5 8 9]


In [32]:
#Reshaping and manipulating arrays
arr = np.array([[1,2,3],[4,5,6]])
reshaped_arr = np.reshape(arr,(3,2))
print(reshaped_arr)


[[1 2]
 [3 4]
 [5 6]]


In [33]:
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [35]:
# Filtering
a = np.array([1,5,8,9,5,9,6,8])
filtering_arr = a[a > 2]
print(filtering_arr)

[5 8 9 5 9 6 8]
